devices:
  - ip: "192.168.73.2"
    username: "test"
    password: "testpassword"

  - ip: "192.168.73.3"
    username: "test1"
    password: "testpassword1"

log_path: "monitoring.log"
max_failures: 3
success_ping_count: 3
smtp_server: "smtp.gmail.com"
smtp_port: 587
sender_email: "yaroslavkuzmin11@gmail.com"
sender_password: "*******"
recipient_email: "Yaroslav_Kuzmin2002@mail.ru"
monitoring_interval: 15
